### ISSUE TITLE
Dashboard URI not updating when using auto-complete

### ISSUE THREAD

**Issue by wolfphantom** [atuttle/Taffy#285] opened 2015-07-20 21:27 UTC
While you are typing in the URI variable to test for a verb the URI submission field is updated.  However, if you complete the field using auto-complete the value does not change in the URI field at the top of the resource panel so it can be tested.

Using auto-complete in (1), does not update the value in (2) so the test can be submitted.

![image](https://cloud.githubusercontent.com/assets/8176629/8787842/09252edc-2efc-11e5-9a1b-ce29e658b577.png)

**Comment by atuttle** [comment] 2015-09-27 20:04
I can't reproduce this issue with the current BER of Taffy. It looks like the same issue that @danshort addressed in #225. At the time we were testing with a simpler regex, but testing it again now with your regex seems to work fine for me.

If you test again and it's still broken for you, please reopen this ticket but indicate any relevant details, like your browser (Chrome, Firefox, etc) and its version, as well as your OS/version.

**Closed by atuttle** 2015-09-27 20:04 UTC
Labels: Difficulty: 1 point, Status: Planned, Type: Bug
